# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: csmock.spec

# add or remove files that should be synced
files_to_sync:
    - csmock.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: csmock
# downstream (Fedora) RPM package name
downstream_package_name: csmock

release_suffix: ""
actions:
    post-upstream-clone: ./make-srpm.sh --generate-spec
    get-current-version: "sed -n 's|^Version: *||p' csmock.spec"

jobs:
    - &copr
      job: copr_build
      trigger: pull_request
      targets:
          - epel-all-aarch64
          - epel-all-ppc64le
          - epel-all-s390x
          - epel-all-x86_64
          - fedora-all-aarch64
          - fedora-all-ppc64le
          - fedora-all-s390x
          - fedora-all-x86_64

    - <<: *copr
      trigger: commit
      owner: "@codescan"
      project: "csutils"
      branch: main
