# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: csmock.spec

# add or remove files that should be synced
files_to_sync:
    - csmock.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: csmock
# downstream (Fedora) RPM package name
downstream_package_name: csmock

srpm_build_deps: [rpm-build]

update_release: false
actions:
    post-upstream-clone: ./make-srpm.sh --generate-spec
    get-current-version: "sed -n 's|^Version: *||p' csmock.spec"

jobs:
    - &copr
      job: copr_build
      trigger: pull_request
      targets:
          - epel-all-aarch64
          - epel-all-ppc64le
          - epel-all-s390x
          - epel-all-x86_64
          - fedora-all-aarch64
          - fedora-all-ppc64le
          - fedora-all-s390x
          - fedora-all-x86_64

    # EPEL tests
    - job: tests
      trigger: pull_request
      targets:
          - epel-7-x86_64
      identifier: epel7
      tf_extra_params:
          environments:
              - artifacts:
                  - type: repository-file
                    id: https://copr.fedorainfracloud.org/coprs/g/codescan/csutils/repo/epel-7/group_codescan-csutils-epel-7
    - job: tests
      trigger: pull_request
      targets:
          - epel-8-aarch64
          - epel-8-x86_64
      identifier: epel8
      tf_extra_params:
          environments:
              - artifacts:
                  - type: repository-file
                    id: https://copr.fedorainfracloud.org/coprs/g/codescan/csutils/repo/epel-8/group_codescan-csutils-epel-8
    - job: tests
      trigger: pull_request
      targets:
          - epel-9-aarch64
          - epel-9-x86_64
      identifier: epel9
      tf_extra_params:
          environments:
              - artifacts:
                  - type: repository-file
                    id: https://copr.fedorainfracloud.org/coprs/g/codescan/csutils/repo/epel-9/group_codescan-csutils-epel-9

    # Fedora tests
    - job: tests
      trigger: pull_request
      targets:
          - fedora-all-aarch64
          - fedora-all-x86_64
      identifier: fedora
      tf_extra_params:
          environments:
              - artifacts:
                  - type: repository-file
                    id: https://copr.fedorainfracloud.org/coprs/g/codescan/csutils/repo/fedora/group_codescan-csutils-fedora

    - <<: *copr
      trigger: commit
      owner: "@codescan"
      project: "csutils"
      branch: main
