#!/usr/bin/perl

use warnings;
use strict;

sub fatal {
    my ($msg) = @_;
    print STDERR "$0: $msg\n";
    exit(1);
}

if ($#ARGV != 0) {
    print STDERR "Usage: $0 COV_DIR\n";
    exit(1);
}

my $dir = $ARGV[0];

fatal("directory not found: $dir")
    unless -d $dir;
fatal("directory not found: $dir/c/emit")
    unless -d "$dir/c/emit";

open(INPUT, '-|', 'cov-format-errors', '--emacs-style', '--dir', "$dir")
    or die;

while (<INPUT>) {
    s/([0-9>]):\n/$1: /;
    s/^Error: /\nError: /;
    s/^path://;
    s/^\/builddir\/build\/BUILD\///;
    print $_;
}

close(INPUT)
    or die;
