---
name: Coverity

on:
  push:
    branches: [main]

jobs:
  coverity:
    if: github.repository == 'csutils/csmock'
    name: Coverity Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Coverity scan
        uses: vapier/coverity-scan-action@v1
        with:
          build_language: other  # other is for Python, etc...
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          project: csutils/csmock

          # The GitHub Action this workflow is based on uses `cov-build`, which
          # does not support buildless capture any more.  This way we make it
          # use `coverity capture` instead of `cov-build`.
          command: --ident; set -x; coverity --ticker-mode=no-spin capture --dir=cov-int --file-include-regex="csmock|scripts"
